/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacatbut;

import java.awt.Color;

/**
 *
 * @author mipt
 */
public class MainForm extends javax.swing.JFrame
{

  /**
   * Creates new form MainForm
   */
  public MainForm()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    txtCat = new javax.swing.JTextField();
    btnCat = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    txtCat.setText("Hello!");

    btnCat.setText("Cat");
    btnCat.setName("..."); // NOI18N
    btnCat.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseEntered(java.awt.event.MouseEvent evt)
      {
        btnCatMouseEntered(evt);
      }
    });
    btnCat.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btnCatActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(49, 49, 49)
        .addComponent(txtCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
        .addComponent(btnCat)
        .addGap(93, 93, 93))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(90, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnCat))
        .addGap(252, 252, 252))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnCatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCatActionPerformed
  {//GEN-HEADEREND:event_btnCatActionPerformed
    if (evt.getSource() == btnCat)
     this.txtCat.setText(((javax.swing.JButton)evt.getSource()).getName());
  }//GEN-LAST:event_btnCatActionPerformed

  private void btnCatMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCatMouseEntered
  {//GEN-HEADEREND:event_btnCatMouseEntered
    this.txtCat.setForeground(Color.blue);
  }//GEN-LAST:event_btnCatMouseEntered

 
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCat;
  private javax.swing.JTextField txtCat;
  // End of variables declaration//GEN-END:variables
}
